const COUNTRY_DATA = [
  ['Afeganistão', 'AF'], ['África do Sul', 'ZA'], ['Albânia', 'AL'], ['Alemanha', 'DE'],
  ['Andorra', 'AD'], ['Angola', 'AO'], ['Antígua e Barbuda', 'AG'], ['Arábia Saudita', 'SA'],
  ['Argélia', 'DZ'], ['Argentina', 'AR'], ['Arménia', 'AM'], ['Austrália', 'AU'], ['Áustria', 'AT'],
  ['Azerbaijão', 'AZ'], ['Bahamas', 'BS'], ['Bahrein', 'BH'], ['Bangladesh', 'BD'],
  ['Barbados', 'BB'], ['Bélgica', 'BE'], ['Belize', 'BZ'], ['Benim', 'BJ'], ['Bielorrússia', 'BY'],
  ['Bolívia', 'BO'], ['Bósnia e Herzegovina', 'BA'], ['Botswana', 'BW'], ['Brasil', 'BR'],
  ['Brunei', 'BN'], ['Bulgária', 'BG'], ['Burkina Faso', 'BF'], ['Burundi', 'BI'], ['Butão', 'BT'],
  ['Cabo Verde', 'CV'], ['Camarões', 'CM'], ['Camboja', 'KH'], ['Canadá', 'CA'], ['Catar', 'QA'],
  ['Cazaquistão', 'KZ'], ['Chade', 'TD'], ['Chile', 'CL'], ['China', 'CN'], ['Chipre', 'CY'],
  ['Colômbia', 'CO'], ['Comores', 'KM'], ['Congo', 'CG'], ['Coreia do Norte', 'KP'],
  ['Coreia do Sul', 'KR'], ['Costa do Marfim', 'CI'], ['Costa Rica', 'CR'], ['Croácia', 'HR'],
  ['Cuba', 'CU'], ['Dinamarca', 'DK'], ['Domínica', 'DM'], ['Egito', 'EG'], ['El Salvador', 'SV'],
  ['Emirados Árabes Unidos', 'AE'], ['Equador', 'EC'], ['Eritreia', 'ER'], ['Eslováquia', 'SK'],
  ['Eslovénia', 'SI'], ['Espanha', 'ES'], ['Estados Unidos da América', 'US'], ['Estónia', 'EE'],
  ['Eswatini', 'SZ'], ['Etiópia', 'ET'], ['Fiji', 'FJ'], ['Filipinas', 'PH'], ['Finlândia', 'FI'],
  ['França', 'FR'], ['Gabão', 'GA'], ['Gâmbia', 'GM'], ['Gana', 'GH'], ['Geórgia', 'GE'],
  ['Granada', 'GD'], ['Grécia', 'GR'], ['Guatemala', 'GT'], ['Guiana', 'GY'], ['Guiné', 'GN'],
  ['Guiné-Bissau', 'GW'], ['Guiné Equatorial', 'GQ'], ['Haiti', 'HT'], ['Honduras', 'HN'],
  ['Hungria', 'HU'], ['Iémen', 'YE'], ['Ilhas Marshall', 'MH'], ['Ilhas Salomão', 'SB'],
  ['Índia', 'IN'], ['Indonésia', 'ID'], ['Irão', 'IR'], ['Iraque', 'IQ'], ['Irlanda', 'IE'],
  ['Islândia', 'IS'], ['Israel', 'IL'], ['Itália', 'IT'], ['Jamaica', 'JM'], ['Japão', 'JP'],
  ['Jordânia', 'JO'], ['Kiribati', 'KI'], ['Kosovo', 'XK'], ['Kuwait', 'KW'], ['Laos', 'LA'],
  ['Lesoto', 'LS'], ['Letónia', 'LV'], ['Líbano', 'LB'], ['Libéria', 'LR'], ['Líbia', 'LY'],
  ['Listenstaine', 'LI'], ['Lituânia', 'LT'], ['Luxemburgo', 'LU'], ['Macedónia do Norte', 'MK'],
  ['Madagáscar', 'MG'], ['Malásia', 'MY'], ['Malawi', 'MW'], ['Maldivas', 'MV'], ['Mali', 'ML'],
  ['Malta', 'MT'], ['Marrocos', 'MA'], ['Maurícias', 'MU'], ['Mauritânia', 'MR'], ['México', 'MX'],
  ['Micronésia', 'FM'], ['Moçambique', 'MZ'], ['Moldávia', 'MD'], ['Mónaco', 'MC'],
  ['Mongólia', 'MN'], ['Montenegro', 'ME'], ['Myanmar', 'MM'], ['Namíbia', 'NA'], ['Nauru', 'NR'],
  ['Nepal', 'NP'], ['Nicarágua', 'NI'], ['Níger', 'NE'], ['Nigéria', 'NG'], ['Noruega', 'NO'],
  ['Nova Zelândia', 'NZ'], ['Omã', 'OM'], ['Países Baixos', 'NL'], ['Palau', 'PW'],
  ['Panamá', 'PA'], ['Papua-Nova Guiné', 'PG'], ['Paquistão', 'PK'], ['Paraguai', 'PY'],
  ['Peru', 'PE'], ['Polónia', 'PL'], ['Portugal', 'PT'], ['Quénia', 'KE'], ['Quirguistão', 'KG'],
  ['Reino Unido', 'GB'], ['República Centro-Africana', 'CF'], ['República Checa', 'CZ'],
  ['República Democrática do Congo', 'CD'], ['República Dominicana', 'DO'], ['Roménia', 'RO'],
  ['Ruanda', 'RW'], ['Rússia', 'RU'], ['Samoa', 'WS'], ['San Marino', 'SM'], ['Santa Lúcia', 'LC'],
  ['São Cristóvão e Nevis', 'KN'], ['São Tomé e Príncipe', 'ST'],
  ['São Vicente e Granadinas', 'VC'], ['Seicheles', 'SC'], ['Senegal', 'SN'], ['Serra Leoa', 'SL'],
  ['Sérvia', 'RS'], ['Singapura', 'SG'], ['Síria', 'SY'], ['Somália', 'SO'], ['Sri Lanka', 'LK'],
  ['Sudão', 'SD'], ['Sudão do Sul', 'SS'], ['Suécia', 'SE'], ['Suíça', 'CH'], ['Suriname', 'SR'],
  ['Tailândia', 'TH'], ['Taiwan', 'TW'], ['Tajiquistão', 'TJ'], ['Tanzânia', 'TZ'],
  ['Timor-Leste', 'TL'], ['Togo', 'TG'], ['Tonga', 'TO'], ['Trindade e Tobago', 'TT'],
  ['Tunísia', 'TN'], ['Turquemenistão', 'TM'], ['Turquia', 'TR'], ['Tuvalu', 'TV'],
  ['Ucrânia', 'UA'], ['Uganda', 'UG'], ['Uruguai', 'UY'], ['Usbequistão', 'UZ'], ['Vanuatu', 'VU'],
  ['Vaticano', 'VA'], ['Venezuela', 'VE'], ['Vietname', 'VN'], ['Zâmbia', 'ZM'], ['Zimbabué', 'ZW'],
];

export const COUNTRIES = COUNTRY_DATA.map(([name, code]) => ({ name, code }));
